export const Equipment = {
  BFG: "Preon Accumulator ",
  Blackhole: "Primordial Cube ",
  BossHunter: "Trophy Hunter's Tricorn ",
  BossHunterConsumed: "Trophy Hunter's Tricorn (Consumed) ",
  BurnNearby: "Helfire Tincture ",
  Cleanse: "Blast Shower ",
  CommandMissile: "Disposable Missile Launcher ",
  CrippleWard: "Effigy of Grief ",
  CritOnUse: "Ocular HUD ",
  DeathProjectile: "Forgive Me Please ",
  DroneBackup: "The Back-up ",
  EliteEarthEquipment: "His Reassurance ",
  EliteFireEquipment: "Ifrit's Distinction ",
  EliteGoldEquipment: "Coven of Gold ",
  EliteHauntedEquipment: "Spectral Circlet ",
  EliteIceEquipment: "Her Biting Embrace ",
  EliteLightningEquipment: "Silence Between Two Strikes ",
  EliteLunarEquipment: "Shared Design ",
  ElitePoisonEquipment: "N'kuhana's Retort ",
  EliteSecretSpeedEquipment: "Beyond the Limits ",
  EliteVoidEquipment: "EQUIPMENT_AFFIXVOID_NAME ",
  EliteYellowEquipment: "",
  Enigma: "EQUIPMENT_ENIGMA_NAME ",
  FireBallDash: "Volcanic Egg ",
  Fruit: "Foreign Fruit ",
  GainArmor: "Jade Elephant ",
  Gateway: "Eccentric Vase ",
  GhostGun: "Reaper's Remorse ",
  GoldGat: "The Crowdfunder ",
  GummyClone: "Goobo Jr. ",
  IrradiatingLaser: "Overloading Excavator ",
  Jetpack: "Milky Chrysalis ",
  LifestealOnHit: "Super Massive Leech ",
  Lightning: "Royal Capacitor ",
  LunarPortalOnUse: "Elegy of Extinction ",
  LunarPotion: "EQUIPMENT_LUNARPOTION_NAME ",
  Meteor: "Glowing Meteorite ",
  Molotov: "Molotov (6-Pack) ",
  MultiShopCard: "Executive Card ",
  OrbOnUse: "EQUIPMENT_ORBONUSE_NAME ",
  OrbitalLaser: "EQUIPMENT_ORBITALLASER_NAME ",
  PassiveHealing: "Gnarled Woodsprite ",
  QuestVolatileBattery: "Fuel Array ",
  Recycle: "Recycler ",
  Saw: "Sawmerang ",
  Scanner: "Radar Scanner ",
  SoulCorruptor: "EQUIPMENT_SOULCORRUPTOR_NAME ",
  SoulJar: "Jar of Souls ",
  TeamWarCry: "Gorag's Opus ",
  Tonic: "Spinel Tonic ",
  VendingMachine: "Remote Caffeinator ",
};

export interface TEquipment {
  [key: string]: string;
}
