name: "Build and Release"
on:
  push:
    tags:        
      - '*'  

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write
    
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      
      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      
      - name: Build step
        run: "deno task build"

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/**"
          body: Download the .exe for windows and the other one without any ending/file extension for linux.
